### ISSUE TITLE
Spinner broken

### ISSUE THREAD

**Issue by vkosuri** [screename/Spinner#1]
Spinner broken, could you please look into this issue?

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from spinner import spinner
>>> s = spinner()
>>>
>>> spintax = s.getSpintax('Everything in moderation, including moderation.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "spinner.py", line 67, in getSpintax
    n, syn = self.getSynonyms(stem)
  File "spinner.py", line 45, in getSynonyms
    for lemma in syn.lemmas:
TypeError: 'instancemethod' object is not iterable
```

**Comment by vkosuri** [comment]
I am using nltk version 3.2
